"""Repair what this program generated, and *only* that.

Why this module exists
----------------------

A cleanup on the machine this was written on deleted
``vigil-shield.conf``. The next inspection noticed immediately -- and then
noticed again 55 times, every cycle, in identical words:
"文件被删除". Nobody rebuilt it. The file that decides which requests reach
the login gate stayed gone until the operator ran ``vigil shield install`` by
hand.

**A report is not a response.** Detection had worked perfectly; the gap was
that nothing in this program ever *did* anything about a finding it already
understood. This module closes that gap for the one class of change where
acting is provably safe: a file this program generates, from data this
program still holds, written by an installer this program can call again.

The boundary is the whole design
--------------------------------

Three kinds of file can show up in a self-integrity finding, and they must be
treated differently:

======================  ==================================================
the file                what happens
======================  ==================================================
generated by vigil      regenerated. It is our own output; rewriting it
                        cannot lose operator data.
vigil's own source      **never touched.** A silent rollback of edited
                        source is the single best way to hide an
                        intrusion: the attacker's change vanishes, the
                        alert is explained away, and nobody investigates.
operator's files        **never touched.** Site vhosts, certificates,
                        their own configuration. Not ours to rewrite.
======================  ==================================================

Two mechanisms enforce that, rather than a promise in a comment:

1. :func:`heal` only ever considers paths that :func:`_registry` recognises
   (a pattern for a file *this program writes*) **and** that the check's own
   discovery -- :func:`vigil.gates.generated_artifacts` -- actually listed as
   one of our artifacts. Source files are inside the package tree and are
   not in that set.
2. The regenerator for each pattern is a named function here. There is no
   generic "write this content back" path that a future caller could point
   at an arbitrary path.

Deliberate non-coverage
-----------------------

A few generated artifacts are **not** auto-rebuilt, because rebuilding them
would rewrite data the operator may have edited by hand or state that is
live:

``config.php`` / ``policy.conf``
    The gate renderer reads these back as its input, deliberately (see
    ``gates._spec_from_current``). Regenerating them from a tampered copy
    would faithfully reproduce the tampering, and regenerating them from
    config.json would silently drop hand-edits. Reported, with the exact
    command that does rebuild them, and left alone.
``patch-settings.py``
    Its content is derived from the operator's own app settings.
``vigil-decoy.conf`` / ``vigil-lure.conf`` / ``vigil-deny.conf`` /
``vigil-gate-*-zones.conf``
    Not covered by :func:`generated_artifacts` today, so the check does not
    watch them and this module therefore will not rewrite them. Widening
    that discovery is a separate change with its own blast radius: the
    config-snippet glob is ``vigil-gate-*.conf``, which a *zone* file also
    matches, and rewriting a live ``limit_req_zone`` key is the one change
    nginx accepts on disk and refuses on reload.

Rate limiting is not decoration
-------------------------------

The failure this guards against is a loop: something deletes the file, we
rebuild it, it is deleted again, we rebuild it -- forever. That is worse than
the original problem, because it burns CPU, fills the audit trail with
identical entries and hides the fact that *something is actively deleting the
file*. So attempts per path are counted in a sliding window; once the cap is
reached the path is reported and left alone, with the reason spelled out.

Every attempt is recorded when it happens, not when it succeeds: an attempt
that crashed must still count against the cap, or a regenerator that dies
halfway becomes an infinite loop.
"""
from __future__ import annotations

import fnmatch
import os
import re
import time
from pathlib import Path

from ..core import shell

__all__ = [
    "heal", "render", "supported", "attempt_allowed", "record_attempt",
    "ACTION_REBUILT", "ACTION_FAILED", "ACTION_LIMITED", "ACTION_UNSUPPORTED",
    "HEAL_STATE_KEY",
]

#: Where the sliding-window attempt counters live inside the check's state.
HEAL_STATE_KEY = "self_integrity_heal"

# -- defaults (config may override; see checks.self_integrity) --------------

DEFAULT_HEAL_WINDOW = 1800
DEFAULT_HEAL_MAX = 3
DEFAULT_DEPLOY_GRACE = 900

ACTION_REBUILT = "rebuilt"
ACTION_FAILED = "failed"
ACTION_LIMITED = "limited"
ACTION_UNSUPPORTED = "unsupported"

#: Patterns for files this program generates, mapped to the action name that
#: rebuilds them. ``fnmatch`` against the absolute path, basename included, so
#: a pattern never has to know the host's prefix.
#:
#: Order matters: the first match wins, so put the specific names first.
_PATTERNS = (
    ("*vigil-shield.conf", "shield"),
    ("*vigil-gate-*.conf", "gate_nginx"),
    ("*/gate.lua", "gate_lua"),
)

#: Human labels for the action names, used in the report.
_ACTION_LABEL = {
    "shield": "重新生成 Web 防护片段（shield.install）",
    "gate_nginx": "重新生成网关 nginx 片段（installer.render_nginx）",
    "gate_lua": "重新生成网关鉴权脚本 gate.lua（installer.render_files）",
}

#: What the operator can run when a file is outside the safe set. Named
#: here so the report and the refusal are the same fact.
_MANUAL = {
    "config.php": "vigil gate reconfigure <kind>（会重写该实例的配置，请先备份）",
    "policy.conf": "vigil gate reconfigure <kind>（会重写该实例的策略，请先备份）",
    "patch-settings.py": "vigil gate reconfigure <kind>",
    "vigil-decoy.conf": "vigil decoy install",
    "vigil-lure.conf": "vigil lure install",
    "vigil-deny.conf": "vigil bouncer install",
}


def action_for(path: str) -> str:
    """The action that rebuilds *path*, or ``""`` when there is none.

    A pure function of the path so the decision can be read (and tested)
    without touching a filesystem.
    """
    name = os.path.basename(str(path))
    for pattern, action in _PATTERNS:
        if fnmatch.fnmatch(str(path), pattern) or fnmatch.fnmatch(name, pattern):
            return action
    return ""


def supported(path: str) -> bool:
    return bool(action_for(path))


def _manual_hint(path: str) -> str:
    name = os.path.basename(str(path))
    hint = _MANUAL.get(name, "")
    if not hint and name.endswith(".conf"):
        hint = "vigil gate reconfigure <kind>"
    return hint or "请人工确认后重建该文件"


# --------------------------------------------------------------------------
# Rate limiting
# --------------------------------------------------------------------------


def _int_cfg(cfg, key: str, default: int, minimum: int = 0) -> int:
    try:
        value = int(cfg.get(key, default))
    except (TypeError, ValueError, AttributeError):
        value = default
    return max(minimum, value)


def attempt_allowed(healstate: dict, path: str, now: float = None,
                    window: int = DEFAULT_HEAL_WINDOW,
                    maximum: int = DEFAULT_HEAL_MAX) -> bool:
    """May we try *path* again yet?

    Counted over a sliding window rather than per hour bucket: a bucket lets
    a badly-timed loop fire twice in two seconds across a boundary, which is
    exactly the loop this is here to bound.
    """
    now = time.time() if now is None else float(now)
    rec = healstate.get(path)
    if not isinstance(rec, dict):
        return True
    stamps = [float(t) for t in (rec.get("attempts") or [])
              if isinstance(t, (int, float))]
    recent = [t for t in stamps if now - t < max(1, int(window))]
    return len(recent) < max(1, int(maximum))


def record_attempt(healstate: dict, path: str, now: float = None,
                   window: int = DEFAULT_HEAL_WINDOW) -> None:
    """Count one attempt, before it is made.

    Recorded first on purpose: an attempt that hangs or crashes still
    consumed a rebuild, and a counter that only advances on success turns a
    crash-looping regenerator into an unbounded one.
    """
    now = time.time() if now is None else float(now)
    rec = healstate.setdefault(path, {})
    if not isinstance(rec, dict):
        rec = {}
        healstate[path] = rec
    stamps = [float(t) for t in (rec.get("attempts") or [])
              if isinstance(t, (int, float))]
    stamps = [t for t in stamps if now - t < max(1, int(window))]
    stamps.append(now)
    rec["attempts"] = stamps
    rec["last"] = now


# --------------------------------------------------------------------------
# Regenerators
# --------------------------------------------------------------------------


def _write_atomic(path, text: str, mode: int = 0o644) -> None:
    from ..gates.installer import _atomic_write
    _atomic_write(path, text, mode)


def _nginx_ok() -> tuple:
    from ..gates import shield
    return shield._nginx_test()


def _nginx_reload() -> None:
    """Reload nginx the same way every other part of this program does.

    A reload is attempted only after ``nginx -t`` has accepted the file, so
    the worst case here is a reload that does not take effect -- which the
    ``runtime_config`` check will report on its own.
    """
    from ..core import detect
    binary = (detect.nginx() or {}).get("binary", "")
    if binary:
        shell.run([binary, "-s", "reload"], timeout=20)


def _regen_shield(path: str) -> dict:
    """Re-run the shield installer.

    ``shield.install`` already has the property this module needs: it writes
    atomically, runs ``nginx -t``, and rolls every byte back if the test
    fails. Reusing it is deliberate -- a second implementation of "write the
    shield safely" would drift from the first, and the drift would show up as
    nginx refusing to load.
    """
    from ..gates import shield
    res = shield.install()
    ok = bool(res.get("ok"))
    detail = ""
    if ok:
        detail = "shield.install 已重写 %s" % path
        if res.get("written"):
            detail += "（写入 %d 个文件）" % len(res["written"])
    else:
        bits = list(res.get("problems") or [])
        if res.get("refused"):
            bits.insert(0, "拒绝：会改动正在生效的 limit_req_zone 键")
        detail = "shield.install 未能完成：%s" % ("；".join(bits) or "原因未知")
    return {"ok": ok, "detail": detail}


def _gate_specs():
    """Every gate instance currently discoverable on this host."""
    from .. import gates
    try:
        return gates.detect_all() or []
    except Exception:                                       # noqa: BLE001
        return []


class _SpecCache:
    """One gate discovery per heal run.

    ``detect_all`` shells out to ``nginx -T``; calling it once per artifact
    would turn a five-file finding into five nginx dumps. The cache is an
    object rather than a module global so two concurrent runs cannot share
    (and therefore cannot stale) each other's view of the host.
    """

    def __init__(self):
        self._done = False
        self._specs = []

    def get(self) -> list:
        if not self._done:
            self._specs = _gate_specs()
            self._done = True
        return self._specs

    def set(self, specs) -> None:
        self._specs = list(specs or [])
        self._done = True


def _resolve_specs(specs, cache) -> list:
    """The instance list to work from: explicit, cached, or freshly read."""
    if specs is not None:
        return list(specs)
    if cache is not None:
        return cache.get()
    return _gate_specs()


def _gate_for_path(path: str, specs=None, cache=None):
    """The gate instance that owns *path*, or ``None``.

    Matched two ways, and both are needed. When the file still exists,
    ``spec.nginx_conf`` points straight at it. When it was *deleted* --
    the case that started this -- detection cannot find it, so the expected
    file name is rebuilt from the instance's slug and compared in the same
    directory. Never a substring match: instance ``log`` must not be able to
    claim instance ``login``'s wiring.
    """
    target = Path(path)
    specs = _resolve_specs(specs, cache)
    for spec in specs:
        if spec.nginx_conf and Path(spec.nginx_conf) == target:
            return spec
    for spec in specs:
        expected = "vigil-gate-%s.conf" % spec.slug
        if target.name == expected:
            return spec
    return None


def _regen_gate_nginx(path: str, specs=None, cache=None) -> dict:
    """Rewrite one gate's nginx snippet, prove nginx still loads, keep it.

    Deliberately **not** ``gates.install()``: that writes the gate's whole
    state directory and re-applies the operator's app patches, which is far
    more than "put this deleted snippet back". Only the snippet is written
    here, and only after ``nginx -t`` accepts it.
    """
    spec = _gate_for_path(path, specs, cache)
    if spec is None:
        return {"ok": False,
                "detail": "找不到该片段对应的网关实例，无法确定它应该是什么内容"}
    try:
        from ..gates import installer, shield
        wanted = installer.render_nginx(spec)
    except Exception as exc:                                # noqa: BLE001
        return {"ok": False, "detail": "渲染失败：%s: %s"
                                       % (type(exc).__name__, exc)}
    if not wanted.strip():
        return {"ok": False, "detail": "渲染结果为空，拒绝写入（空片段会让站点失去防护）"}

    # The v3.2.3 guard, applied *before* a single byte is written: nginx
    # accepts a changed `limit_req_zone` key on disk and refuses it on every
    # reload, so a "repair" that redefines a live zone would take the
    # protection down while looking successful. Repairing a file must never
    # reintroduce the incident this program was just fixed for, so the same
    # check the installer uses runs here too.
    zones_file = Path(getattr(spec, "zones_file", "") or (
        Path(str(path)).parent / ("vigil-gate-%s-zones.conf"
                                  % re.sub(r"\W+", "_", spec.slug))))
    try:
        if zones_file.is_file():
            previous = shield.parse_zone_definitions(
                zones_file.read_text(encoding="utf-8", errors="replace"))
            changes = shield.zone_key_changes(wanted, previous)
            if changes:
                return {"ok": False,
                        "detail": "拒绝重建：这会改动正在生效的 limit_req_zone 键，"
                                  "nginx 会拒绝任何 reload —— %s"
                                  % shield.describe_zone_conflicts(changes)}
    except OSError as exc:
        return {"ok": False, "detail": "无法读取限流区文件，保守起见不重建：%s" % exc}

    old = None
    try:
        if os.path.isfile(path):
            with open(path, "r", encoding="utf-8", errors="replace") as fh:
                old = fh.read()
        _write_atomic(path, wanted, 0o644)
    except OSError as exc:
        return {"ok": False, "detail": "写入失败：%s" % exc}

    ok, out = _nginx_ok()
    if not ok:
        # Put the host back exactly as it was. A snippet that nginx refuses
        # takes every site on the machine down, which is a far worse outcome
        # than a missing snippet.
        try:
            if old is None:
                Path(path).unlink(missing_ok=True)
            else:
                _write_atomic(path, old, 0o644)
        except OSError:
            pass
        _nginx_ok()
        return {"ok": False,
                "detail": "nginx 拒绝重新生成的片段，已还原：%s" % str(out)[-200:]}

    _nginx_reload()
    detail = "已重新生成并写入 %s（%d 字节）" % (path, len(wanted))
    weakened = _weakened(old, wanted)
    if weakened:
        detail += "；" + weakened
    return {"ok": True, "detail": detail}


def _regen_gate_lua(path: str, specs=None, cache=None) -> dict:
    """Rebuild ``gate.lua`` from the instance's live spec.

    Safe to rebuild where ``config.php`` is not: the Lua file is pure
    template output -- every value it interpolates is also stored in
    ``policy.conf``, it is never hand-edited, and it is not an input to its
    own render. Its expected content is known *before* anything is written,
    so a mismatch against the baseline is caught without writing at all.
    """
    state_dir = str(Path(path).parent)
    spec = None
    for cand in _resolve_specs(specs, cache):
        if str(cand.state_dir).rstrip("/") == state_dir.rstrip("/"):
            spec = cand
            break
    if spec is None:
        return {"ok": False, "detail": "找不到该文件所属的网关实例（%s）" % state_dir}
    try:
        from ..gates import installer
        text = installer.render_files(spec)[Path(path)][0]
    except Exception as exc:                                # noqa: BLE001
        return {"ok": False, "detail": "渲染失败：%s: %s"
                                       % (type(exc).__name__, exc)}
    try:
        _write_atomic(path, text, 0o640)
    except OSError as exc:
        return {"ok": False, "detail": "写入失败：%s" % exc}
    return {"ok": True, "detail": "已重新生成 %s（%d 字节）" % (path, len(text))}


def _weakened(before_text, expected_text) -> str:
    """What the tampering took away, as a one-line summary.

    The direction is the whole point: **expected minus before**. A line that
    is in the file this program would write but is *not* in the file that was
    found is a protection that was removed -- the `deny` that was deleted, the
    `access_by_lua_file` that was unhooked, the rate limit that was dropped.
    Those are exactly the lines the rebuild puts back, and they are the only
    part of the difference that says anything about intent.

    Lines that are only in the tampered file are *additions*, and they are not
    reported here: an addition to a generated file cannot survive the rebuild
    anyway, so naming it would be noise (and reporting it as "weakened" would
    be wrong). ``before_text is None`` means there was nothing to compare
    against -- a deleted file -- and gives ``""``.

    Only directive-looking lines are named, and only a handful: a full diff of
    an nginx snippet is noise, and a summary nobody reads is the same as none.
    """
    if before_text is None:
        return ""
    before = set(str(before_text).splitlines())
    expected = set(str(expected_text).splitlines())
    gone = [line.strip() for line in (expected - before) if line.strip()]
    if not gone:
        return ""
    interesting = [line for line in gone if _DIRECTIVE_RX.match(line)]
    shown = interesting or gone
    head = "；".join(shown[:4])
    if len(shown) > 4:
        head += " …… 共 %d 行" % len(shown)
    kind = "被削弱的规则" if interesting else "被改动的行"
    return "%s（%d 行，重建后已恢复）：%s" % (kind, len(shown), head)


#: Directives whose disappearance is a security change worth naming. Kept
#: broad on purpose: a directive we do not list is still counted in the
#: total, it just does not get named individually.
_DIRECTIVE_RX = re.compile(
    r"^(?:deny|allow|limit_req|limit_conn|limit_rate|return|rewrite|proxy_pass"
    r"|access_by_lua_file|auth_basic|ssl_|add_header|include|if|location"
    r"|server_name|listen|error_page|internal)\b")


def _registry(cache=None) -> dict:
    """Action name -> regenerator. Built at call time, not import time, so
    the seam is cheap to replace in tests.

    The gate actions are wrapped so they share the run's single discovery of
    the host's gate instances (see :class:`_SpecCache`).
    """
    return {
        "shield": _regen_shield,
        "gate_nginx": lambda path: _regen_gate_nginx(path, cache=cache),
        "gate_lua": lambda path: _regen_gate_lua(path, cache=cache),
    }


def render(path: str, cache=None) -> tuple:
    """What this module *would* write for *path*, without writing.

    Returns ``(text, err)``. Used to check a rebuild against the stored
    baseline before touching the disk, and kept separate from the writers so
    a caller can never accidentally get one when it wanted the other.
    """
    action = action_for(path)
    if action == "shield":
        from ..gates import shield
        try:
            return shield.render_shield(), ""
        except Exception as exc:                            # noqa: BLE001
            return "", "%s: %s" % (type(exc).__name__, exc)
    if action == "gate_nginx":
        spec = _gate_for_path(path, cache=cache)
        if spec is None:
            return "", "找不到该片段对应的网关实例"
        from ..gates import installer
        return installer.render_nginx(spec), ""
    if action == "gate_lua":
        state_dir = str(Path(path).parent)
        for cand in _resolve_specs(None, cache):
            if str(cand.state_dir).rstrip("/") == state_dir.rstrip("/"):
                from ..gates import installer
                return installer.render_files(cand)[Path(path)][0], ""
        return "", "找不到该文件所属的网关实例"
    return "", "没有可用的重建方式"


# --------------------------------------------------------------------------
# The entry point
# --------------------------------------------------------------------------


def heal(cfg, removed=(), changed=(), baseline=None, healstate=None,
         now: float = None, regenerators=None) -> dict:
    """Try to rebuild generated artifacts that were deleted or altered.

    Returns::

        {"enabled": bool, "attempted": int, "healed": [ {...} ],
         "unhealed": [ {...} ], "limited": [ {...} ],
         "unsupported": [ {...} ], "changed_baseline": {path: digest},
         "baseline": {path: digest}}

    ``changed_baseline`` is the caller's instruction to advance its stored
    digest for the paths that came back: the next run must not re-report a
    file this run has already proven restored, or every later run would burn
    another attempt from the rate limiter on a file that is fine.

    ``baseline`` is the digest map from the last good run, used the only way
    it can be used safely: to check the rebuilt bytes against what we expect
    them to be. A rebuild that does not produce the expected content is *not*
    reported as a success -- it is reported as "written but different", which
    is the honest answer and the one that keeps a tampered environment from
    being silently blessed.
    """
    cfg_ = cfg
    enabled = _bool(cfg_, "checks.self_integrity.auto_recover", True)
    window = _int_cfg(cfg_, "checks.self_integrity.heal_window_seconds",
                      DEFAULT_HEAL_WINDOW, minimum=1)
    maximum = _int_cfg(cfg_, "checks.self_integrity.heal_max_attempts",
                       DEFAULT_HEAL_MAX, minimum=1)
    now = time.time() if now is None else float(now)
    baseline = {str(k): v for k, v in (baseline or {}).items()}
    healstate = healstate if isinstance(healstate, dict) else {}
    cache = _SpecCache()
    regs = regenerators if regenerators is not None else _registry(cache)

    removed = [str(p) for p in removed]
    changed = [str(p) for p in changed]
    out = {"enabled": enabled, "attempted": 0, "healed": [], "unhealed": [],
           "limited": [], "unsupported": [], "changed_baseline": {},
           "baseline": dict(baseline), "window": window, "max": maximum}
    if not enabled:
        return out

    # Deterministic order: the report is a rollout of what happened, and two
    # runs over the same finding should read the same.
    for path in sorted(set(removed) | set(changed)):
        was = "被删除" if path in removed else "被修改"
        action = action_for(path)
        if not action or action not in regs:
            hint = _manual_hint(path)
            out["unsupported"].append({
                "path": path, "was": was, "action": action,
                "reason": "该文件不在可自动重建的范围内（会覆盖你手改过的内容"
                          "或运行时数据），只报告不重建",
                "manual": hint})
            continue
        if not attempt_allowed(healstate, path, now=now, window=window,
                               maximum=maximum):
            tried = len((healstate.get(path) or {}).get("attempts") or [])
            out["limited"].append({
                "path": path, "was": was, "action": action,
                "count": tried, "max": maximum, "window": window,
                "reason": "%d 秒内已尝试重建 %d 次（上限 %d 次）—— 同一文件被"
                          "**反复%s**不是普通故障，而是有人在持续对抗本程序："
                          "继续重建只会陷入「重建→又被删→再重建」的循环，"
                          "并且会把「有东西正在动这个文件」这件事掩盖掉。"
                          "已改为只报警。请人工排查是谁在动它（auditd 有记录）。"
                          % (window, tried, maximum,
                             "删除" if path in removed else "修改")})
            continue

        record_attempt(healstate, path, now=now, window=window)
        out["attempted"] += 1
        # The content on disk *before* the rebuild. Read here because the
        # rebuild is about to destroy it, and the difference between the two
        # is the only record of what the tampering actually did -- which
        # rules it weakened. Read for the changed case only: a deleted file
        # has nothing to compare against.
        before_text = _read_text(path) if path in changed else None
        try:
            res = regs[action](path) or {}
        except Exception as exc:                            # noqa: BLE001
            # A regenerator that raises must not take the inspection down;
            # `safe_run` would turn it into a WARN about the wrong thing.
            res = {"ok": False, "detail": "重建过程异常：%s: %s"
                                          % (type(exc).__name__, exc)}

        # The recheck: is the expected content now on disk, and does it match
        # the baseline we were holding? Kept in its own function because the
        # "rebuilt but different" branch is the one that decides whether this
        # feature tells the truth, and it is worth testing on its own.
        entry = _recheck(path, was, action, res, baseline, cache,
                         before_text=before_text)
        if entry.pop("healed"):
            out["healed"].append(entry)
            out["changed_baseline"][path] = entry["actual"]
        else:
            out["unhealed"].append(entry)

    # Forget counters for paths that are no longer in the finding, so the
    # state file cannot grow one entry per file forever.
    live = set(removed) | set(changed)
    for stale in [p for p in list(healstate) if p not in live]:
        healstate.pop(stale, None)
    return out


def _read_text(path):
    """The file's text, or ``None`` when it cannot be read."""
    try:
        with open(str(path), "r", encoding="utf-8", errors="replace") as fh:
            return fh.read()
    except OSError:
        return None


def _recheck(path: str, was: str, action: str, res: dict, baseline: dict,
             cache=None, before_text=None) -> dict:
    """Decide whether a rebuild actually restored *path*.

    Three outcomes, and the middle one is the whole point:

    * the file is back and its content equals the digest we had for it when
      it was known good  -> a real recovery;
    * the file is back but its content *differs* from that digest, or does
      not match what this program renders from the current configuration
      -> **not a recovery**. Reporting it as one would bless whatever
      changed the inputs, which is exactly how a silent rollback hides an
      intrusion. Reported as a failure with both digests, for a human;
    * the file is still unreadable -> a failure.
    """
    from .checks.selfcheck import digest_file

    expect, render_err = render(path, cache=cache)
    actual = digest_file(path)
    entry = {"path": path, "was": was, "action": action,
             "means": _ACTION_LABEL.get(action, action),
             "detail": res.get("detail", ""),
             "expected": "", "actual": actual, "healed": False}

    if not res.get("ok"):
        return entry
    if actual == "missing" or str(actual).startswith(("unreadable", "too-big")):
        entry["detail"] = "%s；复检仍读不到该文件（%s）" % (
            res.get("detail", ""), actual)
        return entry
    if render_err:
        # Could not compute the expected content independently. The module's
        # own installer reported success and the file is present, so this is
        # called a rebuild -- with the limitation spelled out rather than
        # silently upgraded to "verified".
        entry["healed"] = True
        entry["detail"] = "%s；复检：文件已存在（无法独立核对内容：%s）" % (
            res.get("detail", ""), render_err)
        return entry

    # The intent is in the difference, so it is recorded before anything else
    # can discard it. `expect` is what the file *should* be; `before_text` is
    # what the tampering left behind.
    diff = _weakened(before_text, expect) if before_text is not None else ""
    if diff:
        entry["detail"] = "%s；差异摘要：%s" % (entry["detail"], diff)

    entry["expected"] = _digest_text(expect)
    held = baseline.get(path)
    if held and not str(held).startswith(("missing", "unreadable", "too-big")) \
            and entry["expected"] != held:
        entry["detail"] = (
            "%s；复检：文件已重新生成，但内容与基线不一致"
            "（基线 %s… / 现在渲染出 %s…）。这说明它的输入（配置或实例状态）"
            "也已经变了，请人工核对，不要直接接受。" % (
                res.get("detail", ""), str(held)[:12],
                str(entry["expected"])[:12]))
        return entry

    entry["healed"] = True
    if not held:
        entry["detail"] = ("%s；基线里没有它的哈希（上次记录之后就消失了），"
                           "已按重新生成的内容更新基线" % res.get("detail", ""))
    else:
        entry["detail"] = ("%s；复检：内容与基线一致，已确认恢复"
                           % res.get("detail", ""))
    return entry


def _digest_text(text: str) -> str:
    import hashlib
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _bool(cfg, key: str, default: bool) -> bool:
    try:
        value = cfg.get(key, default)
    except AttributeError:                                  # pragma: no cover
        return default
    if isinstance(value, str):
        return value.strip().lower() in ("1", "true", "yes", "on")
    return bool(default if value is None else value)


# --------------------------------------------------------------------------
# Reporting
# --------------------------------------------------------------------------


def describe(result: dict) -> str:
    """The report block. "" when this run has nothing to say.

    Every action is reported, and every action says which file, why, what
    was done and what the recheck found. A silent auto-repair is not allowed
    here: if the program is rewriting files on the host, the operator is told
    every single time, with the four facts needed to disagree with it.
    """
    if not result:
        return ""
    if not result.get("enabled"):
        return ""
    healed = result.get("healed") or []
    unhealed = result.get("unhealed") or []
    limited = result.get("limited") or []
    unsupported = result.get("unsupported") or []
    if not (healed or unhealed or limited or unsupported):
        return ""

    lines = []
    if healed:
        lines.append("已自动重建 %d 个本程序生成的配置：" % len(healed))
        for e in healed:
            lines.append("       ✅ %s（%s）\n          做了什么：%s\n"
                         "          复检：%s"
                         % (e["path"], e["was"], e.get("means", ""),
                            e.get("detail", "")))
    if unhealed:
        lines.append("尝试重建但**未成功** %d 个：" % len(unhealed))
        for e in unhealed:
            lines.append("       ❌ %s（%s）\n          尝试：%s\n"
                         "          结果：%s"
                         % (e["path"], e["was"], e.get("means", ""),
                            e.get("detail", "")))
    if limited:
        lines.append("**反复被篡改**，已达重建上限、只报警不再重建 %d 个"
                     "（反复对改本身就是主动篡改的签名，按 CRIT 处理）："
                     % len(limited))
        for e in limited:
            lines.append("       ⏳ %s（%s，已尝试 %s/%s 次）\n          %s"
                         % (e["path"], e["was"], e.get("count", "?"),
                            e.get("max", "?"), e.get("reason", "")))
    if unsupported:
        lines.append("不在自动重建范围、只报告 %d 个：" % len(unsupported))
        for e in unsupported:
            lines.append("       ℹ️ %s（%s）\n          %s；人工处理：%s"
                         % (e["path"], e["was"], e.get("reason", ""),
                            e.get("manual", "")))
    return "\n       ".join(lines)
