"""`vigil backup` / `vigil restore` -- the data that cannot be regenerated.

Everything this program *generates* can be regenerated by `vigil update`.
Three things cannot:

* ``secrets.json`` -- the SMTP password, IMAP password, API keys,
* the login gate's ``config.php`` -- which holds the bcrypt hash of the
  operator's password. Lose it and the only way back in is to uninstall the
  gate from a console,
* the learned baselines -- port list, SUID list, file hashes. Lose them and
  every check re-baselines against whatever is on the box *now*, which is
  exactly the wrong thing to do after an incident.

So this is a narrow, deliberate archive: configuration, credentials, gate
state and baselines. Not the picture pool (hundreds of megabytes, and
re-downloadable), not the code (re-deployable), not the logs (they belong to
journald and `/var/log`).

``checks.backup.globs`` is pointed at the output directory, which also wakes
up the `backup_age` inspection -- it had been reporting "未配置备份路径，
跳过备份时效检查" for its whole life, because until now nothing produced a
backup for it to watch.
"""
from __future__ import annotations

import json
import os
import shutil
import tarfile
import zlib
import time
from datetime import datetime
from pathlib import Path

from .. import ui
from ..core import paths, shell
from ..core.config import load as load_config
from ..core.state import read_json, write_json

#: Where archives land by default. Outside /var/lib/vigil so that restoring
#: over the live state directory cannot delete the backup it is restoring.
DEFAULT_DIR = Path("/var/backups/vigil")

#: How many archives to keep. Enough to cover "I broke it yesterday, and the
#: day before" without quietly filling the disk.
KEEP = 14

MANIFEST = "manifest.json"

#: Root the archived gate state directories resolve back to. A module
#: attribute, not a literal in `_destination`, so a test can point restores
#: at a throwaway tree instead of overwriting the live gates -- which the
#: round-trip test used to do (with identical bytes, but still a write to a
#: production path it had no business touching).
GATE_ROOT = Path("/www/server")

#: Where a gate's *site* config lives (`vigil-gate-<name>.conf`). `None` means
#: "ask `detect`", which is the answer that survives being restored on a host
#: laid out differently from the one that made the archive. A hard-coded
#: restore target is how a file ends up in the wrong directory while the
#: operator is told the restore succeeded.
VHOST_ROOT = None


def vhost_dir():
    """The directory a gate's site config belongs in, or None."""
    if VHOST_ROOT:
        return Path(VHOST_ROOT)
    try:
        from ..core import detect
        d = str((detect.panel() or {}).get("vhost_dir") or "")
    except (ImportError, OSError):
        d = ""
    return Path(d) if d else None


def _gate_configs() -> list:
    """Config-ish files inside each installed gate's state directory."""
    out = []
    try:
        from ..gates import generated_artifacts
        out.extend(generated_artifacts())
    except (ImportError, OSError):
        pass
    return sorted({p for p in out if p})


def collect(cfg, include_secrets: bool = True) -> list:
    """The files worth archiving, as (absolute path, archive name)."""
    items = []

    def add(path, arcname, required=False):
        p = Path(path)
        if p.exists() or required:
            items.append((str(p), arcname))

    add(paths.CONFIG, "etc/config.json")
    if include_secrets:
        add(paths.SECRETS, "etc/secrets.json")

    for name in ("health.json", "commandd.json", "threat.json",
                 "login.json", "deploy.json", "avscan.json"):
        src = paths.STATE_STATE / name
        if src.exists():
            add(src, "state/" + name)

    # The gate state directories hold config.php (with the password hash),
    # gate.lua and policy.conf. Their session/image subdirectories are
    # deliberately skipped: large, volatile, and regenerated on demand.
    for path in _gate_configs():
        p = Path(path)
        if not p.is_file():
            continue
        if p.parent.name in ("bt-gate", "dsh-gate") or p.suffix in (
                ".conf", ".php", ".lua"):
            add(p, "gates/%s/%s" % (p.parent.name, p.name))

    for extra in (cfg.get("backup.include", []) or []):
        p = Path(str(extra))
        if p.is_dir():
            for child in sorted(p.rglob("*")):
                if child.is_file():
                    add(child, "extra/%s/%s" % (p.name, child.relative_to(p)))
        else:
            add(p, "extra/%s" % p.name)
    return items


def write_archive(cfg, out_dir=None, include_secrets: bool = True) -> dict:
    """Create one archive. Returns a report dict; never raises on content."""
    from ..version import __version__

    out_dir = Path(out_dir or cfg.get("backup.dir", "") or DEFAULT_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    target = out_dir / ("vigil-backup-%s.tar.gz" % stamp)

    items = collect(cfg, include_secrets)
    manifest = {
        "version": __version__,
        "created": datetime.now().isoformat(timespec="seconds"),
        "hostname": os.uname().nodename,
        "secrets_included": bool(include_secrets),
        "files": [],
    }

    written = 0
    with tarfile.open(str(target), "w:gz") as tar:
        payload = Path.cwd()
        for src, arcname in items:
            try:
                tar.add(src, arcname=arcname)
                written += 1
                manifest["files"].append({
                    "name": arcname,
                    "size": os.path.getsize(src),
                })
            except OSError as e:
                manifest["files"].append({"name": arcname,
                                          "error": str(e)[:120]})
        blob = json.dumps(manifest, ensure_ascii=False, indent=2).encode()
        info = tarfile.TarInfo(MANIFEST)
        info.size = len(blob)
        info.mtime = time.time()
        import io
        tar.addfile(info, io.BytesIO(blob))
        _ = payload

    os.chmod(str(target), 0o600)          # it holds credentials

    # Read it back before telling anyone it worked. A backup that cannot be
    # opened is worse than no backup, because it replaces the worry.
    ok, detail = verify_archive(target)
    return {"path": str(target), "files": written, "verify_ok": ok,
            "verify": detail, "size": target.stat().st_size,
            "secrets": bool(include_secrets)}


def verify_archive(path) -> tuple:
    """Open the archive and check every manifest entry is present.

    Catches EOFError as well as OSError: a truncated gzip does not raise an
    OSError, it raises EOFError from deep inside the decompressor, and a
    verification routine that *crashes* on a damaged archive is worse than
    useless -- it fails while the operator is trying to find out whether
    their backup is any good.
    """
    try:
        with tarfile.open(str(path), "r:gz") as tar:
            names = set(tar.getnames())
            if MANIFEST not in names:
                return False, "归档里没有 %s" % MANIFEST
            member = tar.extractfile(MANIFEST)
            data = json.loads(member.read().decode("utf-8"))
    except (OSError, EOFError, tarfile.TarError, ValueError, zlib.error) as e:
        return False, "无法读取归档：%s: %s" % (type(e).__name__, e)
    missing = [f["name"] for f in data.get("files", [])
               if "error" not in f and f["name"] not in names]
    if missing:
        return False, "归档缺少 %d 个文件：%s" % (len(missing),
                                                 "、".join(missing[:4]))
    return True, "完整（%d 个文件）" % len(data.get("files", []))


def prune(out_dir, keep: int = KEEP) -> int:
    """Delete the oldest archives beyond `keep`."""
    archives = sorted(Path(out_dir).glob("vigil-backup-*.tar.gz"))
    removed = 0
    for old in archives[:-keep] if keep > 0 else []:
        try:
            old.unlink()
            removed += 1
        except OSError:
            pass
    return removed


def cmd_backup(args) -> int:
    cfg = load_config(args.config or None)
    ui.header("备份 vigil", "只备份无法重新生成的东西：配置、凭据、网关状态、基线")

    if args.list:
        out_dir = Path(cfg.get("backup.dir", "") or DEFAULT_DIR)
        archives = sorted(out_dir.glob("vigil-backup-*.tar.gz"))
        if not archives:
            ui.note("还没有备份（%s 下没有归档）" % out_dir)
            return 0
        ui.kv("备份目录", str(out_dir))
        for arc in archives[-10:]:
            age = time.time() - arc.stat().st_mtime
            ui.kv(arc.name, "%.1f MB　%s前"
                  % (arc.stat().st_size / 1048576.0, _human(age)))
        return 0

    if args.prune:
        out_dir = Path(cfg.get("backup.dir", "") or DEFAULT_DIR)
        n = prune(out_dir, int(args.keep or KEEP))
        ui.success("已清理 %d 个过期归档" % n)
        return 0

    include_secrets = not args.no_secrets
    if include_secrets:
        ui.note("归档包含凭据（secrets.json、网关口令哈希），"
                "文件权限 0600，请妥善保管")
    try:
        rep = write_archive(cfg, args.out, include_secrets)
    except OSError as exc:
        ui.failure("备份失败：%s" % exc)
        return 1

    ui.success("已写入 %s" % rep["path"])
    ui.kv("文件数", rep["files"])
    ui.kv("大小", "%.2f MB" % (rep["size"] / 1048576.0))
    if rep["verify_ok"]:
        ui.kv("完整性", "已回读校验：" + rep["verify"])
    else:
        ui.failure("备份校验未通过：%s" % rep["verify"])
        return 1

    out_dir = Path(rep["path"]).parent
    removed = prune(out_dir, int(args.keep or KEEP))
    if removed:
        ui.note("已清理 %d 个过期归档（保留最近 %d 个）"
                % (removed, int(args.keep or KEEP)))

    # Wake up the backup-age inspection. It has been reporting "no backup
    # path configured" since it was written, because nothing produced one.
    pattern = str(out_dir / "vigil-backup-*.tar.gz")
    globs = list(cfg.get("checks.backup.globs", []) or [])
    if pattern not in globs:
        globs.append(pattern)
        cfg.set("checks.backup.globs", globs)
        try:
            cfg.save()
            ui.note("已把备份目录登记到巡检，备份过期会报警")
        except OSError as exc:
            ui.warning("写入配置失败，巡检不会监控备份时效：%s" % exc)
    return 0


def _human(seconds: float) -> str:
    if seconds >= 86400:
        return "%.1f 天" % (seconds / 86400.0)
    if seconds >= 3600:
        return "%.1f 小时" % (seconds / 3600.0)
    return "%d 分钟" % max(1, int(seconds // 60))


def _plan(archive) -> tuple:
    """What the archive holds, and what each entry would overwrite."""
    with tarfile.open(str(archive), "r:gz") as tar:
        member = tar.extractfile(MANIFEST)
        data = json.loads(member.read().decode("utf-8"))
        return data, set(tar.getnames())


def cmd_restore(args) -> int:
    """Put an archive back.

    Always takes a safety backup of the current state first, and refuses to
    write anything until `--yes` is given: this is the command an operator
    reaches for when they are already having a bad day, and the one thing it
    must not do is make it worse by overwriting the only remaining copy of a
    working configuration.
    """
    cfg = load_config(args.config or None)
    archive = Path(args.archive)
    if not archive.is_file():
        ui.failure("找不到归档：%s" % archive)
        return 1

    ok, detail = verify_archive(archive)
    if not ok:
        ui.failure("归档校验失败，拒绝恢复：%s" % detail)
        return 1

    try:
        manifest, names = _plan(archive)
    except (OSError, tarfile.TarError, ValueError) as exc:
        ui.failure("无法读取归档：%s" % exc)
        return 1

    ui.header("恢复 vigil", "从 %s 恢复" % archive.name)
    ui.kv("归档版本", manifest.get("version", "?"))
    ui.kv("备份时间", manifest.get("created", "?"))
    ui.kv("备份主机", manifest.get("hostname", "?"))
    ui.kv("含凭据", "是" if manifest.get("secrets_included") else "否")
    ui.kv("完整性", detail)

    if not manifest.get("secrets_included") and not args.allow_no_secrets:
        ui.warning("这份归档不含凭据，恢复后邮件通道与网关口令需要重新配置")

    targets = []
    for entry in manifest.get("files", []):
        dest = _destination(entry["name"])
        if dest:
            targets.append((entry["name"], dest))
    ui.section("将被覆盖的文件")
    for name, dest in targets[:20]:
        exists = "覆盖" if dest.exists() else "新增"
        ui.out("  %s  %s" % (exists, dest))
    if len(targets) > 20:
        ui.out("  …… 另有 %d 个" % (len(targets) - 20))

    if not args.yes:
        ui.out()
        ui.note("预演结束。确认后加 --yes 执行（会先自动备份当前状态）")
        return 0

    try:
        safety = write_archive(cfg, args.out, include_secrets=True)
        ui.note("已先把当前状态备份到 %s" % safety["path"])
    except OSError as exc:
        ui.failure("恢复前自动备份失败，已中止：%s" % exc)
        return 1

    restored, errors = 0, []
    with tarfile.open(str(archive), "r:gz") as tar:
        for name, dest in targets:
            try:
                member = tar.getmember(name)
                src = tar.extractfile(member)
                if src is None:
                    continue
                dest.parent.mkdir(parents=True, exist_ok=True)
                with open(str(dest), "wb") as fh:
                    shutil.copyfileobj(src, fh)
                # Credentials and gate config must stay unreadable to others.
                if dest.name in ("secrets.json", "config.php"):
                    os.chmod(str(dest), 0o600)
                restored += 1
            except (OSError, KeyError, tarfile.TarError) as exc:
                errors.append("%s: %s" % (name, exc))

    ui.success("已恢复 %d 个文件" % restored)
    for line in errors[:5]:
        ui.warning("恢复失败：%s" % line)

    ui.out()
    ui.hint("恢复后请执行：vigil update（重新生成单元与网关）→ vigil health run")
    return 0 if not errors else 1


def _destination(arcname: str):
    """Map an archive name back to a live path. None means "do not restore"."""
    arcname = str(arcname)
    if arcname == "etc/config.json":
        return Path(paths.CONFIG)
    if arcname == "etc/secrets.json":
        return Path(paths.SECRETS)
    if arcname.startswith("state/"):
        return paths.STATE_STATE / Path(arcname).name
    if arcname.startswith("gates/conf/"):
        # The nginx snippets. Resolved to wherever *this* host keeps its nginx
        # configuration -- an archive must not bake in a path that is only
        # correct on the machine that produced it. Leaving these out of the
        # mapping is worse than not archiving them at all: a file that appears
        # in the backup and is silently skipped on restore teaches the
        # operator that it was restored.
        try:
            from ..gates import shield
            return shield.conf_dir() / Path(arcname).name
        except (ImportError, OSError):
            return None
    if arcname.startswith("gates/nginx/"):
        # The gate's *site* config lives in the panel's vhost directory, not
        # under /www/server/<gate>/. It was archived and had no destination, so
        # restoring reported success while leaving the site's gate config
        # behind -- precisely the failure the round-trip invariant exists to
        # catch, and the reason this file refuses to archive what it cannot put
        # back. Resolved through `detect` for the same reason `gates/conf/`
        # is: an archive must not bake in one host's paths.
        parts = Path(arcname).parts
        if len(parts) < 3 or not parts[2]:
            return None          # 只有目录、没有文件名：不该给它编一个目标
        base = vhost_dir()
        return (base / parts[2]) if base else None
    if arcname.startswith("gates/"):
        parts = Path(arcname).parts
        # Any installed instance, not just the two historical directory
        # names: every `--name` instance's state directory ends in `-gate`.
        # Without the general rule, a named login gate's `config.php` -- the
        # only copy of its password hash -- was archived but restored
        # nowhere, and the operator would believe it had come back.
        if len(parts) >= 3 and parts[1].endswith("-gate"):
            return GATE_ROOT / parts[1] / parts[2]
        return None
    if arcname.startswith("extra/"):
        return None          # operator-added paths are advisory only
    return None


def register(sub) -> None:
    p = sub.add_parser(
        "backup", help="备份配置、凭据、网关状态与巡检基线",
        description="只备份无法重新生成的东西。代码与图片不备份——它们可以重新"
                    "部署或下载；凭据与登录网关的口令哈希丢了则只能从控制台重来。")
    p.add_argument("--out", default="", help="输出目录（默认 /var/backups/vigil）")
    p.add_argument("--no-secrets", action="store_true",
                   help="不包含 secrets.json（更安全，但恢复后要重配邮件）")
    p.add_argument("--keep", type=int, default=KEEP, help="保留最近几个归档")
    p.add_argument("--list", action="store_true", help="列出现有归档")
    p.add_argument("--prune", action="store_true", help="只清理过期归档")
    p.set_defaults(func=cmd_backup)

    p = sub.add_parser(
        "restore", help="从归档恢复（默认只预演，加 --yes 才写入）",
        description="把备份写回本机。执行前一定会先自动备份当前状态，"
                    "所以恢复本身可以反悔。")
    p.add_argument("archive", help="归档路径（.tar.gz）")
    p.add_argument("--yes", action="store_true", help="确实执行（否则只看计划）")
    p.add_argument("--allow-no-secrets", action="store_true",
                   help="归档不含凭据时也继续")
    p.add_argument("--out", default="", help="恢复前自动备份的输出目录")
    p.set_defaults(func=cmd_restore)
